"""Flask security helpers for local backend channel.

- Random loopback port selection + retry on conflict
- Per-launch backend token generated by the launcher (Electron)
- /health endpoint that returns the expected launch nonce
- @require_backend_token decorator validates every API call
"""

from __future__ import annotations

import functools
import os
import secrets
from typing import Optional

from flask import Flask, jsonify, request


ENV_TOKEN = "CAM_BACKEND_TOKEN"
ENV_NONCE = "CAM_BACKEND_NONCE"


_backend_token: Optional[str] = None
_backend_nonce: Optional[str] = None


def set_token(token: str, nonce: str) -> None:
    """Called once by the launcher after the backend process starts."""
    global _backend_token, _backend_nonce
    _backend_token = token
    _backend_nonce = nonce


def get_token_from_env() -> Optional[str]:
    return os.environ.get(ENV_TOKEN)


def get_nonce_from_env() -> Optional[str]:
    return os.environ.get(ENV_NONCE)


def generate_token() -> str:
    return secrets.token_urlsafe(32)


def generate_nonce() -> str:
    return secrets.token_hex(16)


def require_backend_token(fn):
    """Decorator that rejects requests without the correct backend token."""
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        expected = _backend_token or get_token_from_env()
        if not expected:
            # No token configured means launcher is misconfigured.
            return jsonify({"error": "backend token not configured"}), 401

        header_token = request.headers.get("X-Backend-Token")
        query_token = request.args.get("backend_token")
        supplied = header_token or query_token

        if not supplied or not secrets.compare_digest(supplied, expected):
            return jsonify({"error": "unauthorized"}), 401
        return fn(*args, **kwargs)
    return wrapper


def register_health(app: Flask) -> None:
    @app.route("/health")
    def health():
        nonce = _backend_nonce or get_nonce_from_env()
        return jsonify({
            "status": "ok",
            "nonce": nonce or "",
        })
